language: node_js
node_js:
  - 11
cache:
  directories:
  - node_modules
before_install:
  - yarn global add firebase-tools
after_success:
  - yarn release
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master